name: Gaaflora Galleries Photography
markdown: redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'autolink', 'strikethrough']
pygments: true
exclude:
- README.md
- id_rsa
- id_rsa.enc
prose:
  rooturl: '_posts'
  siteurl: 'http://beta.gaaflora.com/'
  media: 'media'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "published"
        field:
          element: "hidden"
          value: true
      - name: "title"
        field:
          element: "text"
          label: "title"
